# Greetings Hyrax developer, you may be surprised to see this file.
# Hyrax is moving to using Postgresql for testing in CircleCI and
# hopefully by Hyrax developers during local development. Previously,
# we used sqlite.
#
# And while installing Postgresql is beyond the scope of this
# community, I (Jeremy) installed Postgresql via homebrew (brew.sh),
# and have used the following for testing (note `hyrax-testup` is
# defined later on):
#
# ```console
# hyrax-testup
# brew services start postgresql
# export DATABASE_URL="postgresql://localhost:5432/internal_development"
# bundle exec rspec
# ```
#
# But, before running that, I have a shell alias (see
# https://github.com/jeremyf/dotzshrc/blob/trunk/configs/aliases.zsh)
# that I call.  The alias ensures that I have:
#
#   * clean set of solr indices
#   * running solr indices
#   * running fcrepo
#   * running redis server
#
# ```console
# alias hyrax-testup='cd $HOME/git/samvera/hyrax/.internal_test_app ; \
#   rm -rf tmp/solr-valkyrie-test/server/solr/hyrax-valkyrie-test ; \
#   rm -rf tmp/solr-test/server/solr/hydra-test ; \
#   fcrepo_wrapper --config config/fcrepo_wrapper_test.yml & \
#   solr_wrapper --config config/solr_wrapper_test.yml & \
#   solr_wrapper --config config/solr_wrapper_valkyrie_test.yml & \
#   redis-server &'
# ```
#
# Best luck, and I (Jeremy) hope to add this to the Wiki at some point
# once this current code is accepted into the main-line.
rails_options:
  - "--database=postgresql" # Caution, as you may only get "one option" until this is merged. https://github.com/cbeer/engine_cart/pull/102
